/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `celestial_voyage` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `celestial_voyage`;

CREATE TABLE IF NOT EXISTS `comments` (
  `ID_Comments` int NOT NULL AUTO_INCREMENT,
  `Comments_Users` int NOT NULL,
  `Date` datetime NOT NULL,
  `Text` text NOT NULL,
  `Comments_Cosmic-objects` int NOT NULL,
  `Likes` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID_Comments`),
  KEY `FK_Comments_Users` (`Comments_Users`),
  KEY `FK_Comments_Cosmic-objects` (`Comments_Cosmic-objects`),
  CONSTRAINT `FK_Comments_Cosmic-objects` FOREIGN KEY (`Comments_Cosmic-objects`) REFERENCES `cosmic-objects` (`ID_Cosmic-objects`),
  CONSTRAINT `FK_Comments_Users` FOREIGN KEY (`Comments_Users`) REFERENCES `users` (`ID_users`)
) ENGINE=InnoDB AUTO_INCREMENT=93 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `comments` (`ID_Comments`, `Comments_Users`, `Date`, `Text`, `Comments_Cosmic-objects`, `Likes`) VALUES
	(2, 1, '2024-05-30 22:47:31', 'OMG it is really cool', 2, 11),
	(3, 1, '2024-05-30 22:49:23', 'The planets in our solar system are so fascinating and full of wonder!', 3, 12),
	(5, 1, '2024-05-30 22:50:33', 'Each planet has its unique beauty and characteristics. Truly amazing!', 4, 6),
	(6, 1, '2024-05-30 22:50:39', 'I love how diverse the planets are, from the fiery Mercury to the icy Neptune!', 5, 5),
	(10, 1, '2024-05-30 22:52:03', 'Uranus\' blue-green hue is simply stunning!', 7, 3),
	(11, 1, '2024-05-30 22:52:18', 'I can\'t get enough of the incredible images of the planets from space missions!', 8, 0),
	(12, 1, '2024-05-30 22:52:45', 'Learning about planets is like exploring a whole new world each time!', 9, 0),
	(13, 1, '2024-05-30 22:52:56', 'Saturn\'s rings are absolutely breathtaking!', 6, 7),
	(14, 35, '2024-05-30 22:58:39', 'Learning about planets is like exploring a whole new world each time!', 1, 13),
	(15, 35, '2024-05-30 22:58:54', 'Venus\' brightness is so beautiful in the night sky!', 2, 20),
	(16, 35, '2024-05-30 22:59:16', 'Planets like Earth remind us of the delicate balance needed to sustain life.', 3, 0),
	(17, 35, '2024-05-30 22:59:27', 'Mars\' mysterious landscape always sparks my imagination.', 4, 8),
	(18, 35, '2024-05-30 22:59:46', 'The more we learn about planets, the more we appreciate the universe\'s complexity.', 5, 5),
	(19, 35, '2024-05-30 22:59:58', 'The discovery of new exoplanets continues to amaze and inspire us!', 6, 8),
	(20, 35, '2024-05-30 23:00:11', 'The formation of planets from stardust is a beautiful story of creation.', 7, 4),
	(21, 35, '2024-05-30 23:01:29', 'I love imagining what it would be like to stand on the surface of another planet.', 8, 0),
	(22, 35, '2024-05-30 23:01:41', 'It\'s incredible to think about the possibilities of life on other planets.', 9, 0),
	(23, 36, '2024-05-30 23:03:37', 'Each planet\'s story is a testament to the wonders of cosmic evolution.', 1, 4),
	(24, 36, '2024-05-30 23:10:13', 'The variety of moons orbiting the planets is equally fascinating!', 2, 28),
	(25, 36, '2024-05-30 23:10:25', 'The formation of planets from stardust is a beautiful story of creation.', 3, 3),
	(26, 36, '2024-05-30 23:10:36', 'The gas giants like Jupiter and Saturn are so majestic and awe-inspiring.', 5, 8),
	(27, 36, '2024-05-30 23:10:46', 'The planets remind us of the incredible vastness and beauty of our universe.', 4, 4),
	(28, 36, '2024-05-30 23:11:12', 'The exploration of planets showcases humanity\'s curiosity and drive for discovery!', 6, 10),
	(29, 36, '2024-05-30 23:11:19', 'Planets are the ultimate playgrounds for the imagination!', 7, 5),
	(30, 36, '2024-05-30 23:11:27', 'The mystery of Neptune\'s dark spots is endlessly intriguing!', 8, 0),
	(31, 36, '2024-05-30 23:11:47', 'The history of planetary exploration is filled with milestones of human achievement.', 9, 0),
	(32, 37, '2024-05-30 23:14:36', 'Each planet\'s unique characteristics make them all worth exploring and understanding.', 7, 8),
	(33, 37, '2024-05-30 23:14:49', 'The planets remind us of the endless possibilities and wonders of the universe.', 8, 0),
	(34, 37, '2024-05-30 23:15:05', 'The possibility of life on other planets makes the study of them incredibly exciting!', 9, 0),
	(35, 37, '2024-05-30 23:15:17', 'The gas giants\' immense size and beauty are awe-inspiring.', 7, 8),
	(36, 37, '2024-05-30 23:15:39', 'The ancient myths and legends about planets add a layer of cultural richness.', 1, 7),
	(38, 37, '2024-05-30 23:16:16', 'So true i really appreciate that', 3, 3),
	(40, 37, '2024-05-30 23:17:05', 'Stars light up the night sky with their brilliant beauty!', 10, 27),
	(41, 37, '2024-05-30 23:17:15', 'Each star is a unique and magnificent beacon in the universe.', 11, 7),
	(42, 37, '2024-05-30 23:17:21', 'The sheer number of stars in the sky fills me with awe and wonder!', 12, 4),
	(44, 37, '2024-05-30 23:17:37', 'Stars are the sparkling gems of the cosmos.', 14, 6),
	(45, 37, '2024-05-30 23:17:43', 'The birth and death of stars are incredible processes to study!', 15, 4),
	(46, 37, '2024-05-30 23:17:49', 'The colors of stars, from blue to red, are simply stunning', 16, 0),
	(47, 37, '2024-05-30 23:17:59', 'Binary star systems, where two stars orbit each other, are fascinating!', 17, 0),
	(48, 37, '2024-05-30 23:18:05', 'he study of stars helps us understand the origins and evolution of the universe.', 18, 0),
	(49, 37, '2024-05-30 23:18:22', 'The variety of star clusters, from open to globular, showcases the diversity of the cosmos.', 19, 0),
	(50, 38, '2024-05-30 23:19:42', 'The fact that some planets have auroras is simply magical!', 1, 5),
	(52, 38, '2024-05-30 23:20:41', 'The ongoing study of planets helps us prepare for future space travel.', 3, 4),
	(53, 38, '2024-05-30 23:20:49', 'Well done!', 4, 18),
	(54, 38, '2024-05-30 23:20:55', 'Good', 6, 10),
	(56, 38, '2024-05-30 23:21:13', 'Stars are the building blocks of galaxies, creating a breathtaking tapestry in space.', 11, 8),
	(57, 38, '2024-05-30 23:21:19', 'Stars remind us of the vastness and mystery of the universe.', 12, 6),
	(58, 38, '2024-05-30 23:21:26', 'The sheer number of stars in the sky fills me with awe and wonder!', 13, 9),
	(59, 38, '2024-05-30 23:21:30', 'Cute!', 14, 13),
	(60, 38, '2024-05-30 23:21:36', 'Stars light up the night sky with their brilliant beauty!', 15, 4),
	(61, 38, '2024-05-30 23:21:42', 'The light from stars travels millions of years to reach us, connecting us to the distant past.', 16, 0),
	(62, 38, '2024-05-30 23:21:53', 'The colors of stars, from blue to red, are simply stunning', 17, 0),
	(63, 38, '2024-05-30 23:22:06', 'Wow...didnt know that', 18, 0),
	(88, 1, '2024-06-04 23:57:42', 'I love sun!', 10, 4),
	(89, 1, '2024-06-04 23:58:41', 'Cool!', 10, 6),
	(90, 1, '2024-06-05 00:00:55', 'I wish we have more information about this star..', 12, 3),
	(91, 1, '2024-06-05 00:02:12', 'Wow that was interesting !', 13, 0),
	(92, 1, '2024-06-05 00:04:15', 'wonderful wonderful!', 19, 1);

CREATE TABLE IF NOT EXISTS `contact-me` (
  `ID_contact-me` int NOT NULL AUTO_INCREMENT,
  `Email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Subject` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`ID_contact-me`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `contact-me` (`ID_contact-me`, `Email`, `Subject`, `Content`) VALUES
	(14, 'james.anderson@astroresearch.org', 'Exploring the Wonders of Stars Survey Invitation', 'I hope this email finds you well. My name is James Anderson, and I am currently conducting a research project on the fascinating world of stars. I am reaching out to you because your insights would be incredibly valuable to my study.Stars are not only beautiful celestial objects that light up our night sky but also vital components of the universe that help us understand its origins and evolution. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about stars.Thank you for your time and valuable contribution!'),
	(15, 'john.harris@cosmicresearch.org', 'Exploring the Mysteries of Black Holes', 'My name is John Harris, and I am currently conducting a research project on the enigmatic nature of black holes. I am reaching out to you because your insights would be incredibly valuable to my study.Black holes are among the most mysterious and fascinating objects in the universe. They challenge our understanding of physics and hold secrets about the very fabric of space and time. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about black holes.'),
	(16, 'laura.mitchell@exoplanetresearch.org', 'The Search for Exoplanets Survey Invitation', 'My name is Laura Mitchell, and I am currently conducting a research project on the search for exoplanets. I am reaching out to you because your insights would be incredibly valuable to my study.Exoplanets are planets that orbit stars outside our solar system, and their discovery has opened up exciting possibilities for finding other habitable worlds. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about exoplanets.'),
	(17, 'steven.clark@galaxyevolution.org', 'The Evolution of Galaxies Survey Invitation', 'Galaxies are massive systems of stars, gas, dust, and dark matter, bound together by gravity. Studying their evolution helps us understand the history and future of the universe. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about galaxies.What aspect of galaxy evolution do you find most fascinating?'),
	(18, 'david.wilson@darkmatterstudy.org', 'Understanding Dark Matter', 'My name is David Wilson, and I am currently conducting a research project on the elusive concept of dark matter. I am reaching out to you because your insights would be incredibly valuable to my study.Dark matter is a form of matter that does not emit light or energy, making it invisible and detectable only through its gravitational effects. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about dark matter.What do you find most intriguing about the concept of dark matter?'),
	(19, 'laura.mitchell@exoplanetresearch.org', 'The Search for Exoplanets', 'Exoplanets are planets that orbit stars outside our solar system, and their discovery has opened up exciting possibilities for finding other habitable worlds. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about exoplanets.How excited are you about the possibility of discovering habitable exoplanets?'),
	(25, 'robert.martin@milkywayresearch.org', 'Exploring the Wonders of the Milky Way Survey Inv', 'I hope this email finds you well. My name is Robert Martin, and I am currently conducting a research project on the Milky Way galaxy. I am reaching out to you because your insights would be incredibly valuable to my study.The Milky Way is our home galaxy, a vast collection of stars, planets, and cosmic wonders. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about the Milky Way.What do you find most fascinating about the Milky Way galaxy?'),
	(26, 'emma.richards@spacefuture.org', 'The Future of Space Exploration Survey Invitation', 'I hope this email finds you well. My name is Emma Richards, and I am currently conducting a research project on the future of space exploration. I am reaching out to you because your insights would be incredibly valuable to my study.What upcoming space missions are you most excited about?'),
	(27, 'peter.collins@cosmicphenomena.org', 'Understanding Cosmic Phenomena  Survey Invitation', 'I hope this email finds you well. My name is Peter Collins, and I am currently conducting a research project on various cosmic phenomena. I am reaching out to you because your insights would be incredibly valuable to my study.Cosmic phenomena such as supernovae, gamma-ray bursts, and cosmic rays are fascinating events that offer a glimpse into the dynamic nature of the universe. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about these phenomena.'),
	(28, 'linda.roberts@spaceweatherresearch.org', 'The Impact of Space Weather Survey Invitation', 'I hope this email finds you well. My name is Linda Roberts, and I am currently conducting a research project on the impact of space weather. I am reaching out to you because your insights would be incredibly valuable to my study.Space weather, including solar flares and geomagnetic storms, can have significant effects on our technology and daily lives. Your participation in this survey will contribute significantly to a deeper understanding of public perception and knowledge about space weather.How aware are you of the impacts of space weather on Earth?');

CREATE TABLE IF NOT EXISTS `cosmic-objects` (
  `ID_Cosmic-objects` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Content` text NOT NULL,
  `Mass` float NOT NULL,
  `Area` float NOT NULL,
  `Speed` float NOT NULL,
  `Cosmic-objects_object-class` int NOT NULL,
  `Cosmic-objects_type` int NOT NULL,
  `Views` int unsigned NOT NULL DEFAULT '0',
  `Object` blob NOT NULL,
  PRIMARY KEY (`ID_Cosmic-objects`),
  KEY `FK_Cosmic-objects_type` (`Cosmic-objects_type`),
  KEY `FK_Cosmic-objects_object-class` (`Cosmic-objects_object-class`),
  CONSTRAINT `FK_Cosmic-objects_object-class` FOREIGN KEY (`Cosmic-objects_object-class`) REFERENCES `object-class` (`ID_Object-class`),
  CONSTRAINT `FK_Cosmic-objects_type` FOREIGN KEY (`Cosmic-objects_type`) REFERENCES `type` (`ID_Type`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `cosmic-objects` (`ID_Cosmic-objects`, `Name`, `Content`, `Mass`, `Area`, `Speed`, `Cosmic-objects_object-class`, `Cosmic-objects_type`, `Views`, `Object`) VALUES
	(1, 'Mercury\r\n\r\n', 'Mercury\'s surface is heavily cratered and resembles that of the Moon. It has numerous impact craters and basins, the largest being the Caloris Basin, which is about 1,550 kilometers (960 miles) in diameter. The surface also features cliffs, or "scarps," that were likely formed as the planet cooled and contracted.\r\nMercury has a large metallic core, making up about 85% of the planet\'s radius. The core\'s size and composition suggest that Mercury may have formed under different conditions than the other terrestrial planets or that it lost much of its outer layers due to a massive impact early in its history.', 0.32868, 74.8, 172.332, 1, 1, 1468, _binary 0x6d6572637572792e737667),
	(2, 'Venus\r\n\r\n\r\n\r\n', 'Venus is the second planet from the Sun and similar in size to Earth. It has a thick, toxic atmosphere that traps heat, making it the hottest planet. Its surface is covered with volcanoes and vast plains, and it rotates very slowly in the opposite direction to most planets.\r\nRaising surface temperatures to around 465°C (870°F), hotter than Mercury. Venus has clouds of sulfuric acid and surface features including vast plains, highland regions, and volcanic mountains. It rotates very slowly, taking about 243 Earth days to complete one rotation.', 4.81068, 460.2, 126.072, 1, 1, 265, _binary 0x76656e75732e737667),
	(3, 'Earth\r\n\r\n\r\n\r\n', 'Earth is the third planet from the Sun in our solar system and the only known celestial body to support life. It is the fifth-largest planet in our solar system and is often referred to as the "Blue Planet" due to the abundance of water on its surface, giving it a distinct blue appearance when viewed from space.\r\nEarth\'s surface is approximately 71% water and 29% land. The highest point on Earth is the summit of Mount Everest, standing at 29,029 feet (8,848 meters) above sea level. Conversely, the lowest point on land is the shoreline of the Dead Sea, located about 1,410 feet (430 meters) below sea level. Earth is also the only known place in the universe where life has been discovered.', 5.976, 510.1, 107.218, 1, 1, 282, _binary 0x65617274682e737667),
	(4, 'Mars\r\n\r\n\r\n\r\n', 'Mars, the fourth planet from the Sun, is known as the Red Planet due to its reddish appearance. It has the largest volcano and canyon in the solar system and shows signs of ancient river beds and lakes. Mars has a thin atmosphere and experiences cold temperatures.\r\nMars has a thin atmosphere, mostly carbon dioxide, and experiences seasons similar to Earth. Scientists are particularly interested in Mars because of evidence suggesting it once had liquid water, raising the possibility of past life.', 0.63345, 144.8, 86.868, 1, 1, 224, _binary 0x6d6172732e737667),
	(5, 'Jupiter\r\n\r\n\r\n\r\n', 'Jupiter is the fifth planet from the Sun and the largest in our solar system. It\'s a gas giant made mostly of hydrogen and helium. Jupiter has a Great Red Spot, which is a massive storm, and many moons, including the largest moon, Ganymede.\r\nIt has a dynamic atmosphere with colorful bands and spots, the most famous being the Great Red Spot, a storm larger than Earth that has raged for at least 400 years. Jupiter has at least 79 moons, including Ganymede, the largest moon in the solar system, which is even bigger than Mercury.', 1876.64, 614.18, 47.051, 1, 2, 311, _binary 0x6a7570697465722e737667),
	(6, 'Saturn\r\n\r\n\r\n\r\n', 'Saturn, the sixth planet from the Sun, is famous for its stunning ring system made of ice and rock particles. It\'s a gas giant like Jupiter and has numerous moons, including Titan, which has a thick atmosphere and lakes of liquid methane.\r\nTitan, Saturn\'s largest moon, is notable for its dense atmosphere and surface lakes of liquid methane and ethane. Saturn\'s atmosphere is mostly hydrogen and helium, and it has strong winds and storms.', 561.804, 42.7, 34.821, 1, 2, 162, _binary 0x73617475726e2e737667),
	(7, 'Uranus\r\n\r\n', 'Uranus is the seventh planet from the Sun and has a blue-green color due to methane in its atmosphere. It\'s an ice giant with a tilted axis, causing it to rotate on its side. Uranus has faint rings and several moons.\r\nIts atmosphere contains hydrogen, helium, and methane, which gives it a blue-green color. Uranus has faint rings and at least 27 known moons. Its unusual tilt is thought to be the result of a collision with an Earth-sized object long ago.', 86.0544, 8.083, 24.477, 1, 3, 268, _binary 0x7572616e75732e737667),
	(8, 'Neptune', 'Neptune, the eighth planet from the Sun, is similar in composition to Uranus and has a deep blue color. It\'s known for its strong winds and storms, including the Great Dark Spot. Neptune has rings and many moons, with Triton being the largest.\r\nIt has the strongest winds in the solar system, with speeds up to 2,100 kilometers per hour (1,300 miles per hour). Neptune has six known rings and at least 14 moons, with Triton being the largest. Triton is geologically active, with geysers that shoot nitrogen gas into space.', 101.592, 7.618, 19.566, 1, 3, 210, _binary 0x6e657074756e652e737667),
	(9, 'Pluto\r\n\r\n', 'Pluto is a dwarf planet located in the Kuiper Belt, a region of icy bodies beyond Neptune. It\'s known for its heart-shaped glacier and has five moons, with Charon being the largest. Pluto has a rocky core surrounded by ice and a thin atmosphere.\r\nIts surface is a mix of frozen nitrogen, methane, and carbon monoxide, and it has a thin atmosphere that expands and contracts as it orbits the Sun. Pluto\'s largest moon, Charon, is about half its size, and the two bodies are tidally locked, always showing the same face to each other.', 0.01195, 16.7, 17.096, 1, 4, 110, _binary 0x706c75746f2e737667),
	(10, 'Sun', 'The Sun is the closest star to Earth and the center of our solar system. It is a yellow dwarf star that provides light and heat necessary for life on Earth. The Sun is composed mainly of hydrogen and helium and is currently in the main sequence phase of its life.\r\nSun provides the essential heat and light necessary for life on Earth. Composed primarily of hydrogen and helium, the Sun is currently in its main sequence phase, where it converts hydrogen into helium through nuclear fusion in its core.', 1989000, 6.08, 828.021, 2, 11, 225, _binary 0x73756e2e737667),
	(11, 'Aldebaran', 'Aldebaran, a K5III type red giant, is the brightest star in the constellation Taurus and one of the most luminous stars in the night sky.Aldebaran moves through space at a speed of 54,000 km/h. Located about 65 light-years from Earth, this star has expanded and cooled after depleting its hydrogen core, giving it a reddish-orange appearance. \r\n Aldebaran is the brightest star in the constellation Taurus and one of the brightest stars in the night sky. As a red giant, Aldebaran has expanded and cooled after exhausting the hydrogen in its core. It appears reddish-orange and is located about 65 light-years from Earth.Aldebaran\'s impressive size and brightness make it a prominent feature in the winter sky.', 2307000, 24494.7, 54.153, 2, 5, 97, _binary 0x616c6465626172616e2e737667),
	(12, 'Arcturus', 'Arcturus is the brightest star in the constellation Boötes and the fourth brightest star in the night sky. It is an orange giant star located approximately 37 light-years from Earth. Arcturus has exhausted the hydrogen in its core and expanded, becoming cooler and more luminous.\r\nArcturus travels at a remarkable speed of 122,000 km/h. Situated approximately 37 light-years from Earth, Arcturus has exhausted the hydrogen in its core and expanded into a cooler, more luminous giant. Its distinctive orange hue and rapid motion relative to other stars have made it a subject of extensive study in astronomy.', 2148000, 8104.32, 122.686, 2, 5, 67, _binary 0x61726374757275732e737667),
	(13, 'Capella', 'Capella is the brightest star in the constellation Auriga and the sixth brightest star in the night sky. It is actually a system of four stars in two binary pairs. The primary components are two giant stars. Capella is located about 42 light-years from Earth.\r\nCapella, a G8III type giant star, is the brightest star in the constellation Auriga and the sixth brightest star in the night sky. Capella is actually a complex star system consisting of two binary pairs.Capella\'s brightness and proximity make it an important object for both amateur and professional astronomers.', 5372000, 1803.31, 39.034, 2, 7, 48, _binary 0x636170656c6c612e737667),
	(14, 'Deneb', 'Deneb is the brightest star in the constellation Cygnus and one of the most luminous stars known. It is a blue-white supergiant star located approximately 2,600 light-years from Earth. Deneb forms part of the Summer Triangle asterism.\r\nDeneb, an A2Iae type supergiant, is the brightest star in the constellation Cygnus and one of the most luminous stars known. Located approximately 2,600 light-years from Earth, Deneb is a blue-white supergiant that forms part of the Summer Triangle asterism. Its incredible luminosity and distance make it a key marker in the night sky, used by navigators and stargazers alike.', 37791000, 518224, 194.401, 2, 8, 77, _binary 0x64656e65622e737667),
	(15, 'Polaris', 'Polaris, also known as the North Star, is the brightest star in the constellation Ursa Minor. It is a supergiant star and is famous for being nearly directly aligned with Earth\'s rotational axis, making it an important navigational star. Polaris is about 433 light-years from Earth.\r\nPolaris, classified as an F7Ib supergiant, is famously known as the North Star due to its nearly fixed position in the sky relative to the North Pole.Polaris is a triple star system, with the main component being a supergiant. It serves as an important navigational star and is a cornerstone in celestial navigation and star lore. ', 10740000, 31415.9, 77.425, 2, 8, 55, _binary 0x706f6c617269732e737667),
	(16, 'Promixa', 'Proxima Centauri is the closest known star to the Sun, located about 4.24 light-years away in the constellation Centaurus. It is a red dwarf star and part of the Alpha Centauri star system. Despite its proximity, Proxima Centauri is not visible to the naked eye due to its low luminosity.\r\nProxima Centauri, an M5.5Ve type red dwarf, is the closest known star to the Sun, located about 4.24 light-years away in the constellation Centaurus.Despite its proximity, it is not visible to the naked eye due to its low luminosity. Proxima Centauri is part of the Alpha Centauri star system and has been a focus of study due to its potential for hosting habitable exoplanets.', 242658, 0.061, 54.468, 2, 9, 35, _binary 0x61726374757275732e737667),
	(17, 'Rigel', 'Rigel is the brightest star in the constellation Orion and one of the brightest stars in the night sky. It is a blue supergiant star located about 860 light-years from Earth. Rigel is highly luminous and significantly larger and more massive than the Sun.\r\nRigel, a B8Ia type supergiant, is the brightest star in the constellation Orion and one of the most prominent stars in the night sky.Located approximately 860 light-years from Earth, Rigel is a blue supergiant that is significantly larger and more massive than the Sun. Its intense brightness and striking blue color make it a key feature of the winter sky and a favorite among astronomers.', 41770000, 78211.1, 73.821, 2, 8, 54, _binary 0x726967656c2e737667),
	(18, 'Sirius', 'Sirius, also known as the Dog Star, is the brightest star in the night sky. It is a binary star system consisting of Sirius A, a main-sequence star, and Sirius B, a faint white dwarf. Sirius is located approximately 8.6 light-years from Earth and is part of the constellation Canis Major.\r\nSirius, an A1V type main sequence star, is the brightest star in the night sky and part of the constellation Canis Major. Located about 8.6 light-years from Earth, Sirius is a binary star system consisting of Sirius A, a bright main-sequence star, and Sirius B, a faint white dwarf. The brilliance of Sirius and its significance in various cultures have made it a prominent and well-studied star.', 4017000, 17.79, 64.325, 2, 10, 48, _binary 0x7369726975732e737667),
	(19, 'Vega', 'Vega is the brightest star in the constellation Lyra and the fifth brightest star in the night sky. It is a main-sequence star that is relatively close to Earth at about 25 light-years away. Vega is part of the Summer Triangle asterism and has been extensively studied by astronomers.\r\nVega, classified as an A0V type main sequence star, is the brightest star in the constellation Lyra and the fifth brightest star in the night sky.Located about 25 light-years from Earth, Vega is one of the most studied stars in the sky. It serves as a cornerstone for the Summer Triangle asterism and has been used as a reference point in astronomical observations. ', 2022000, 2.362, 54.369, 2, 10, 52, _binary 0x7572616e75732e737667);

CREATE TABLE IF NOT EXISTS `cosmic_calendar` (
  `ID_Calendar` int NOT NULL AUTO_INCREMENT,
  `Date` date NOT NULL,
  `Content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`ID_Calendar`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `cosmic_calendar` (`ID_Calendar`, `Date`, `Content`) VALUES
	(1, '2024-05-27', 'As we approach the New Moon on May 27, the skies are growing darker, making it an ideal time to prepare for deep-sky observations. This is a great period to familiarize yourself with stargazing apps like Star Walk or Stellarium, which can help you identify celestial objects and plan your observations.\r\nThe Moon and Jupiter will be in conjunction tonight, appearing close together in the sky. This pairing offers a striking visual and is an excellent target for binoculars or a small telescope. Observing the two bright objects together is a treat for any stargazer.'),
	(2, '2024-05-28', 'Today marks the summer solstice, the longest day of the year in the Northern Hemisphere. Celebrate the solstice by watching the sunset and then stargazing as the sky darkens. The solstice is a great time to reflect on the changing seasons and the motions of the Earth.\r\nJune’s Full Moon, known as the Strawberry Moon, rises tonight. Named by Native American tribes for the strawberry harvest season, this Full Moon will be a bright and beautiful sight. Enjoy the moonrise and use binoculars or a telescope to explore its features. Try capturing the Moon with landscape elements in the foreground for stunning photographs. '),
	(3, '2024-05-29', 'The Lagoon Nebula (M8) is a large and bright nebula in the constellation Sagittarius. It is visible to the naked eye under dark skies and spectacular through binoculars or a telescope. Look for the star cluster embedded within the nebula and the dark lanes that give it a lagoon-like appearance.\r\nThe night after the Full Moon, the sky remains bright, but you can still enjoy stargazing. Focus on bright stars and constellations, and use this time to learn the sky. Identifying major stars like Arcturus, Spica, and Antares will help you navigate the night sky more easily. Try locating the bright stars of the Summer Triangle: Vega, Deneb, and Altair.'),
	(4, '2024-05-30', 'In the early morning of May 30, Mars and Saturn will be in close proximity. This rare conjunction offers a unique opportunity to observe both planets in the same field of view through a telescope. Mars’ reddish hue contrasts beautifully with Saturn’s yellowish color and ring system. Try to capture this event with your telescope and camera for a stunning image.\r\nWith the Moon now moving past its Full phase, deep-sky observing becomes easier. Focus on observing nebulae and star clusters in the summer sky. Targets like the Eagle Nebula (M16) and the Wild Duck Cluster (M11) are well-positioned for observation.'),
	(5, '2024-05-31', 'With the New Moon just a day away, tonight’s sky will be exceptionally dark. This is perfect for deep-sky observations. Head to a location far from city lights and use a telescope or binoculars to explore galaxies, nebulae, and star clusters. Look for the Andromeda Galaxy, the Orion Nebula, and the Pleiades star cluster.\r\nTake a night to learn about exoplanets—planets that orbit stars outside our solar system. While they are not visible through amateur telescopes, you can explore resources online and watch documentaries to understand the methods used to discover these distant worlds and the possibility of life beyond Earth.'),
	(6, '2024-06-01', 'The New Moon marks the beginning of a new lunar cycle. With no moonlight to interfere, the night sky is at its darkest. This is the best time for astrophotography and deep-sky observations. Capture long-exposure images of the Milky Way and try to spot distant objects like the Whirlpool Galaxy (M51) or the Sombrero Galaxy (M104).\r\nTonight, the Moon will pass close to Saturn. This conjunction offers another chance to observe Saturn’s rings and its largest moon, Titan, along with the bright lunar surface. Use a telescope to appreciate the details of both celestial bodies.'),
	(7, '2024-06-02', 'On the evening the Moon and Venus will appear close together in the western sky after sunset. Venus will shine brightly, making it easy to locate. This conjunction is a beautiful sight and an excellent opportunity for photography. Use a wide-angle lens to capture both celestial bodies in the same frame.\r\nThe Ring Nebula (M57) in the constellation Lyra is a beautiful planetary nebula. It appears as a small, ring-like structure and is best observed with a telescope. Look for its delicate ring shape and the central star that created it.'),
	(8, '2024-06-03', 'With the Moon and Venus still close together, tonight offers another chance to observe this conjunction. Additionally, look for other bright planets like Jupiter and Saturn, which will be visible in the evening sky. Use a telescope to view Jupiter’s cloud bands and moons, as well as Saturn’s stunning rings.\r\nAs the Moon wanes towards its Last Quarter, it will be in a beautiful crescent phase tonight, appearing near Venus in the evening sky. This sight is perfect for photography and casual observation. Use binoculars to enhance your view of this celestial pairing.'),
	(9, '2024-06-04', 'Spend the evening learning and identifying constellations. Use a stargazing app or star chart to locate and recognize major constellations like Ursa Major, Orion, and Scorpius. This foundational knowledge will enhance your stargazing experience and help you navigate the night sky more easily.\r\nWith the New Moon just a day away, tonight’s sky will be exceptionally dark. This is perfect for deep-sky observations. Head to a location far from city lights and use a telescope or binoculars to explore galaxies, nebulae, and star clusters. Look for the Andromeda Galaxy, the Orion Nebula, and the Pleiades star cluster.'),
	(10, '2024-06-05', 'With the New Moon phase continuing, tonight is perfect for observing the Milky Way. Find a dark location with a clear view of the horizon, away from city lights. The Milky Way will appear as a faint, milky band stretching across the sky. Use binoculars to explore its dense star fields and dark nebulae.\r\nWith the Moon and Venus still close together, tonight offers another chance to observe this conjunction. Additionally, look for other bright planets like Jupiter and Saturn, which will be visible in the evening sky. Use a telescope to view Jupiter’s cloud bands and moons, as well as Saturn’s stunning rings. For added interest, track the motion of Jupiter’s moons over several hours.'),
	(11, '2024-06-06', 'The Arietids meteor shower peaks on the night of June 4. This is one of the strongest daytime meteor showers, but you can also see meteors in the early morning hours before dawn. Find a dark location and look towards the Aries constellation for the best chance of spotting meteors.\r\nMoon and Venus will appear close together in the western sky after sunset. Venus will shine brightly, making it easy to locate. This conjunction is a beautiful sight and an excellent opportunity for photography. Use a wide-angle lens to capture both celestial bodies in the same frame. After observing the conjunction, scan the sky for other bright stars like Regulus in Leo and Spica in Virgo.'),
	(12, '2024-06-07', 'Tonight, focus on observing the visible planets. Jupiter, Saturn, and Mars will be prominent in the night sky. Use a telescope to explore the cloud bands of Jupiter, the rings of Saturn, and the surface details of Mars. Jupiter’s Galilean moons—Io, Europa, Ganymede, and Callisto—are also fascinating to observe.\r\nhe New Moon marks the beginning of a new lunar cycle. With no moonlight to interfere, the night sky is at its darkest. This is the best time for astrophotography and deep-sky observations. Capture long-exposure images of the Milky Way and try to spot distant objects like the Whirlpool Galaxy (M51) or the Sombrero Galaxy (M104). '),
	(13, '2024-06-08', 'Double stars are pairs of stars that appear close to each other in the sky. Some famous double stars to observe include Mizar and Alcor in the handle of the Big Dipper, and Albireo in the constellation Cygnus. Use a telescope to split these stars and appreciate their contrasting colors and brightness.\r\nSpend the evening learning and identifying constellations. Use a stargazing app or star chart to locate and recognize major constellations like Ursa Major, Orion, and Scorpius. This foundational knowledge will enhance your stargazing experience and help you navigate the night sky more easily. Challenge yourself to find lesser-known constellations like Delphinus.'),
	(14, '2024-06-09', 'The First Quarter Moon offers excellent viewing conditions for the lunar surface. The stark shadows along the terminator highlight craters, mountains, and valleys. Use a telescope to explore the Moon’s rugged terrain, focusing on prominent features like the Apennine mountain range and the crater Copernicus.\r\nWith the New Moon phase continuing, tonight is perfect for observing the Milky Way. Find a dark location with a clear view of the horizon, away from city lights. The Milky Way will appear as a faint, milky band stretching across the sky. Use binoculars to explore its dense star fields and dark nebulae. Look for the Great Rift, a series of dark dust clouds that divide the Milky Way lengthwise.'),
	(15, '2024-06-10', 'Check your local schedule for the ISS flyover times tonight. The ISS will appear as a bright, fast-moving object crossing the sky. After the ISS passes, try to spot other satellites. Apps like Heavens-Above can help you identify and track satellites in real time.\r\nThis is one of the strongest daytime meteor showers, but you can also see meteors in the early morning hours before dawn. Find a dark location and look towards the Aries constellation for the best chance of spotting meteors. Early morning hours are optimal, and you might spot a few bright meteors streaking across the sky.'),
	(16, '2024-06-11', 'Venus reaches its greatest eastern elongation, making it visible in the evening sky after sunset. It will be at its highest point above the horizon and will shine brilliantly. This is the best time to observe Venus and appreciate its brightness. Use a telescope to see its phase, which will appear similar to a crescent moon.\r\nTonight, focus on observing the visible planets. Jupiter, Saturn, and Mars will be prominent in the night sky. Use a telescope to explore the cloud bands of Jupiter, the rings of Saturn, and the surface details of Mars. Jupiter’s Galilean moons—Io, Europa, Ganymede, and Callisto—are also fascinating to observe. Note their changing positions over the night, a testament to their rapid orbits around Jupiter.'),
	(17, '2024-06-12', 'Star clusters are groups of stars that are gravitationally bound. Two types of star clusters to observe are open clusters and globular clusters. Open clusters like the Pleiades (M45) and the Beehive Cluster (M44) are best viewed with binoculars, while globular clusters like M13 in Hercules require a telescope.\r\nDouble stars are pairs of stars that appear close to each other in the sky. Some famous double stars to observe include Mizar and Alcor in the handle of the Big Dipper, and Albireo in the constellation Cygnus. '),
	(18, '2024-06-13', 'The Summer Triangle is an asterism formed by the bright stars Vega, Deneb, and Altair. It becomes prominent in the evening sky during the summer months. Use this asterism as a guide to explore the constellations Lyra, Cygnus, and Aquila. Each of these constellations contains interesting deep-sky objects to observe.\r\nThe First Quarter Moon offers excellent viewing conditions for the lunar surface. The stark shadows along the terminator highlight craters, mountains, and valleys. Use a telescope to explore the Moon’s rugged terrain, focusing on prominent features like the Apennine mountain range and the crater Copernicus. '),
	(19, '2024-06-14', 'As the Moon approaches its Full Moon phase, continue observing its changing appearance. Focus on different features each night, such as the large lunar maria (dark plains), mountain ranges, and prominent craters. The play of light and shadow across the lunar surface creates a dynamic and ever-changing view.\r\nCheck your local schedule for the ISS flyover times tonight. The ISS will appear as a bright, fast-moving object crossing the sky. After the ISS passes, try to spot other satellites. Apps like Heavens-Above can help you identify and track satellites in real time. '),
	(20, '2024-06-15', 'Tomorrow is the Full Moon, so tonight is a good time to prepare for lunar photography. Plan your location and equipment setup to capture the moonrise or moonset. Experiment with different camera settings to achieve sharp and detailed images of the lunar surface.\r\nVenus reaches its greatest eastern elongation, making it visible in the evening sky after sunset. It will be at its highest point above the horizon and will shine brilliantly. This is the best time to observe Venus and appreciate its brightness. Use a telescope to see its phase, which will appear similar to a crescent moon. '),
	(21, '2024-06-16', 'June’s Full Moon, known as the Strawberry Moon, rises tonight. Named by Native American tribes for the strawberry harvest season, this Full Moon will be a bright and beautiful sight. Enjoy the moonrise and use binoculars or a telescope to explore its features. Try capturing the Moon with landscape elements in the foreground for stunning photographs.\r\nStar clusters are groups of stars that are gravitationally bound. Two types of star clusters to observe are open clusters and globular clusters. Open clusters like the Pleiades (M45) and the Beehive Cluster (M44) are best viewed with binoculars, while globular clusters like M13 in Hercules require a telescope. For a challenge, try finding the Wild Duck Cluster (M11) in Scutum.'),
	(22, '2024-06-17', 'The night after the Full Moon, the sky remains bright, but you can still enjoy stargazing. Focus on bright stars and constellations, and use this time to learn the sky. Identifying major stars like Arcturus, Spica, and Antares will help you navigate the night sky more easily.\r\nMoon and Mars will be close together in the sky. This conjunction is a great opportunity to observe both celestial bodies. Use a telescope to see Mars’ surface details and the Moon’s craters. This close pairing will be a striking sight. Additionally, observe the Moon’s Tycho crater, known for its prominent rays'),
	(23, '2024-06-18', 'Jupiter will be well-placed for observation tonight. Use a telescope to view its cloud bands and the Great Red Spot. Watch as its four largest moons—Io, Europa, Ganymede, and Callisto—change positions throughout the night. These Galilean moons offer a dynamic and fascinating view.\r\nThe Summer Triangle is an asterism formed by the bright stars Vega, Deneb, and Altair. It becomes prominent in the evening sky during the summer months. Use this asterism as a guide to explore the constellations Lyra, Cygnus, and Aquila. Each of these constellations contains interesting deep-sky objects to observe. Look for the Ring Nebula (M57) in Lyra and the North America Nebula (NGC 7000) in Cygnus.'),
	(24, '2024-06-19', 'Saturn is also prominent in the night sky. Its rings are easily visible with a small telescope, and even binoculars can reveal its oblate shape. Look for Titan, Saturn’s largest moon, which will appear as a bright point of light near the planet.\r\nAs the Moon approaches its Full Moon phase, continue observing its changing appearance. Focus on different features each night, such as the large lunar maria (dark plains), mountain ranges, and prominent craters. The play of light and shadow across the lunar surface creates a dynamic and ever-changing view. Tonight, look for the Sea of Tranquility, where Apollo 11 landed.'),
	(25, '2024-06-20', 'Tonight is a good time to observe asteroids. Use online resources like the Minor Planet Center to find information on which asteroids are visible. Small telescopes can reveal these rocky bodies as they move against the backdrop of stars.\r\nTomorrow is the Full Moon, so tonight is a good time to prepare for lunar photography. Plan your location and equipment setup to capture the moonrise or moonset. Experiment with different camera settings to achieve sharp and detailed images of the lunar surface. Practice framing the Moon with foreground elements like trees or buildings.');

CREATE TABLE IF NOT EXISTS `object-class` (
  `ID_Object-class` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`ID_Object-class`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `object-class` (`ID_Object-class`, `Name`) VALUES
	(1, 'Planet'),
	(2, 'Stellar');

CREATE TABLE IF NOT EXISTS `type` (
  `ID_Type` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(25) NOT NULL,
  PRIMARY KEY (`ID_Type`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `type` (`ID_Type`, `Name`) VALUES
	(1, 'Terrestrial Planet'),
	(2, 'Gas Giant'),
	(3, 'Ice Giant'),
	(4, 'Dwarf Planet'),
	(5, 'Red Giant'),
	(7, 'Giant Star'),
	(8, 'Supergiant'),
	(9, 'Red Dwarf'),
	(10, 'Main Sequence Star'),
	(11, 'Star');

CREATE TABLE IF NOT EXISTS `users` (
  `ID_users` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Surname` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Birthdate` date NOT NULL,
  `Password` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Avatar` blob,
  `Admin` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID_users`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `users` (`ID_users`, `Name`, `Surname`, `Email`, `Birthdate`, `Password`, `Avatar`, `Admin`) VALUES
	(1, 'Milena', 'Kobercova', '11DPMKobercova@rvt.lv', '2005-01-05', 'Qwerty123', _binary 0x2f696d672f70726f66696c652f617661746172732d70726f66696c652f617374726f6e6175742d68656c6d65742e706e67, 1),
	(2, 'Yurij', 'Kolypatov', 'yurka.cool@yandex.ru', '1976-05-12', 'Ribka1984', _binary 0x2f696d672f70726f66696c652f617661746172732d70726f66696c652f626561722e706e67, 0),
	(3, 'Anastasiya', 'Spagina', 'nastya.spagetti@mail.ru', '1987-04-13', 'Iamemo1337', _binary 0x2f696d672f70726f66696c652f617661746172732d70726f66696c652f6769726c2e706e67, 0),
	(35, 'Alise', 'Pienina', 'Alise.Pienina@gmail.com', '1987-04-11', 'Poioy321', _binary 0x2f696d672f70726f66696c652f617661746172732d70726f66696c652f776f6d616e202831292e706e67, 0),
	(36, 'Vladlens', 'Podnebess', '11DPVPodnebess@rvt.com', '2005-04-15', 'Bvcxz567', _binary 0x2f696d672f70726f66696c652f617661746172732d70726f66696c652f6d616e2e706e67, 1),
	(37, 'Jelena', 'Kuragova', 'Jelena.Kuragova@gmail.com', '1967-04-01', 'Kakis846', _binary 0x2f696d672f70726f66696c652f617661746172732d70726f66696c652f7365612d6c696f6e2e706e67, 0),
	(38, 'Artem', 'Zubarev', 'Artem.Zubarev@yahoo.co', '1999-12-14', 'Opagan8274', _binary 0x2f696d672f70726f66696c652f617661746172732d70726f66696c652f70726f66696c652d7069632e6a7067, 0),
	(62, 'Alyona', 'Pupovidka', 'alyo@yahoo.com', '1998-02-12', 'IlovedogsS32', NULL, 0),
	(63, 'Pyotr', 'Alexandrovich', 'petja.axela@mail.ru', '1965-09-21', 'Aloha43', _binary 0x2f696d672f70726f66696c652f617661746172732d70726f66696c652f617374726f6e617574202833292e706e67, 0),
	(64, 'Anna', 'Uzbekovna', 'anna.voyage@index.lv', '2004-04-12', 'Annalavki21', NULL, 0);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
